{
  "id": 1455411,
  "global_id": "Z2lkOi8vaGFja2Vyb25lL1JlcG9ydC8xNDU1NDEx",
  "url": "https://hackerone.com/reports/1455411",
  "title": "Invalid handling of X509_verify_cert() internal errors in libssl (CVE-2021-4044)",
  "state": "Closed",
  "substate": "resolved",
  "severity_rating": "medium",
  "readable_substate": "Resolved",
  "created_at": "2022-01-20T14:31:29.038Z",
  "submitted_at": "2022-01-20T14:31:29.100Z",
  "is_member_of_team?": false,
  "is_organization_group_member?": false,
  "reporter": {
    "disabled": false,
    "username": "tniessen",
    "url": "/tniessen",
    "profile_picture_urls": {
      "small": "/assets/avatars/default-14ffa99f59cd01423c64904352cc130ffcb6a802eadfd11777a54485749e60f2.png"
    },
    "is_me?": false,
    "cleared": false,
    "verified": false,
    "hackerone_triager": false,
    "hacker_mediation": false
  },
  "team": {
    "id": 54349,
    "url": "https://hackerone.com/ibb",
    "handle": "ibb",
    "profile_picture_urls": {
      "small": "https://hackerone-us-west-2-production-attachments.s3.us-west-2.amazonaws.com/variants/v0qywgoh5hm4cbhuanu8mqdtowhr/235acf2ba808c3a51a94888fb977392c26f8fb0ccf77a81a4546c5e4065c06f1?response-content-disposition=inline%3B%20filename%3D%22ibb%20revision%205%20copy.png%22%3B%20filename%2A%3DUTF-8%27%27ibb%2520revision%25205%2520copy.png&response-content-type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQGK6FURQ7G4OCRFL%2F20250921%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20250921T003636Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEH8aCXVzLXdlc3QtMiJGMEQCIDGN6xRXkipIqeD39%2FtstUVrQkeHhl%2FxhvDuWUHEJgsgAiBcJw8vwBpE3IzuTr3fqr2M9V6SwVQHEIisgKuKMJVoWyq7BQj4%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDAxMzYxOTI3NDg0OSIMfc22FeItlB7fsFn%2FKo8Ffm5Vqp0OLe5pV1PeqgQWzDTuU4FqowWH1fjAMotLjDQx0AvmjSuLkx8nHIR3F9EcWNhI1buvDphOuSY3oD4T4WVLQjTUCaMjN3e%2Fv741055XG5OPXCe1oEb8eWqfcx%2Ff5jVOG7FoFGMQs25WHeUIB3rpzR%2FVVQuoRKv5KLz6lGI8wn3uquTw05jVNXa7qngHd%2FJH1eY4P9%2BGoYYpVfQmWzjROMHwa2x0sJk5QfPMqXyamTGOs5V0NSbkOtc0pXBibCpzjFV4I2WWEhj5EnzdWD8s%2FAO5UvaoYzZQ2brwSrINS9bNyuQFAwWfH0KDjjtYzt9ye0p%2FNKTecEh20UFVidMGzwuwRHWc9Cq5ycYqCUZIFmA9GbQvBknj3PSBdPZFRotUt4j8i0rMlsoAie28maE%2FXLI6q2%2BrACzFa%2B3HqG38IS95u7kjj%2BQfZA0pjGNrh3gpJQHn9GdTbc4vN4GVOZPSqV%2FFkq7ghOZQ4fzCYQRfWs9ELAyAidng9JhSn2dNMoI05u%2FM%2BbP0h3qqILA2%2Fh2gt9DdzecwEXUHoIa7f9d0jG%2BDm2aCOYZ9Hle3Faq12GA%2FG26%2BCKb9KFyODx40P%2Fz5R2pYw5v0KgRaP%2BUYb7x4dok%2B38i7vFKWjfXmYVh2p9BYr0eXnfuIkhfQSy8FLuc%2BcqsQqKEGmEuVSO0SErDAOTV2RRodc3hu1ovCoNpjY8TLQqphyfm2c1vyeXEdqCmkSX55Ia9wT3XppjXji276gS3D5RBQuScemfR5keTR5u6B5Z2T%2F3Wf066KyQOBwe9YC2RDTypy%2F12MDBpO3ubGJBYMa%2FxURNt82yFwt4cfofeiJLAfNZXk%2BfkWYPevp40d%2B0snkPba1D8FtCQwyTDD47zGBjqyAfxTAeYaM3mZJ9o9BCgJhn0d8fXS%2FO6ZTTxqrwSftYi8Jrf11R2oMKWnlWzzVoJCsIkeWYs0cxytRs7N6KE1FSSB1Y5MkbxC98vs%2BQeNI3eYXBXj0%2BUpkJLE8Q74gL1lWJo%2B5D4p7WJlG3g%2BBA%2BLW9UFTQ44c2Js2TFR9b0AJGhj5mVyEt5u%2BT%2FsuRpGhrcAkcNiKLEx7K5l36DsSOHZ4JSggc43FWLv76erQxZm%2FIqyKvo%3D&X-Amz-SignedHeaders=host&X-Amz-Signature=12414f9af9ec6866dac29ca244e8eae8b029ee81a44b6ee9b522ff5c1531be3f",
      "medium": "https://hackerone-us-west-2-production-attachments.s3.us-west-2.amazonaws.com/variants/v0qywgoh5hm4cbhuanu8mqdtowhr/3f1ab5c6a9b6dadada1e6c8121700b884388bd0a43471fee1897a38ce57d0b2c?response-content-disposition=inline%3B%20filename%3D%22ibb%20revision%205%20copy.png%22%3B%20filename%2A%3DUTF-8%27%27ibb%2520revision%25205%2520copy.png&response-content-type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAQGK6FURQ7G4OCRFL%2F20250921%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20250921T003636Z&X-Amz-Expires=3600&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEH8aCXVzLXdlc3QtMiJGMEQCIDGN6xRXkipIqeD39%2FtstUVrQkeHhl%2FxhvDuWUHEJgsgAiBcJw8vwBpE3IzuTr3fqr2M9V6SwVQHEIisgKuKMJVoWyq7BQj4%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAMaDDAxMzYxOTI3NDg0OSIMfc22FeItlB7fsFn%2FKo8Ffm5Vqp0OLe5pV1PeqgQWzDTuU4FqowWH1fjAMotLjDQx0AvmjSuLkx8nHIR3F9EcWNhI1buvDphOuSY3oD4T4WVLQjTUCaMjN3e%2Fv741055XG5OPXCe1oEb8eWqfcx%2Ff5jVOG7FoFGMQs25WHeUIB3rpzR%2FVVQuoRKv5KLz6lGI8wn3uquTw05jVNXa7qngHd%2FJH1eY4P9%2BGoYYpVfQmWzjROMHwa2x0sJk5QfPMqXyamTGOs5V0NSbkOtc0pXBibCpzjFV4I2WWEhj5EnzdWD8s%2FAO5UvaoYzZQ2brwSrINS9bNyuQFAwWfH0KDjjtYzt9ye0p%2FNKTecEh20UFVidMGzwuwRHWc9Cq5ycYqCUZIFmA9GbQvBknj3PSBdPZFRotUt4j8i0rMlsoAie28maE%2FXLI6q2%2BrACzFa%2B3HqG38IS95u7kjj%2BQfZA0pjGNrh3gpJQHn9GdTbc4vN4GVOZPSqV%2FFkq7ghOZQ4fzCYQRfWs9ELAyAidng9JhSn2dNMoI05u%2FM%2BbP0h3qqILA2%2Fh2gt9DdzecwEXUHoIa7f9d0jG%2BDm2aCOYZ9Hle3Faq12GA%2FG26%2BCKb9KFyODx40P%2Fz5R2pYw5v0KgRaP%2BUYb7x4dok%2B38i7vFKWjfXmYVh2p9BYr0eXnfuIkhfQSy8FLuc%2BcqsQqKEGmEuVSO0SErDAOTV2RRodc3hu1ovCoNpjY8TLQqphyfm2c1vyeXEdqCmkSX55Ia9wT3XppjXji276gS3D5RBQuScemfR5keTR5u6B5Z2T%2F3Wf066KyQOBwe9YC2RDTypy%2F12MDBpO3ubGJBYMa%2FxURNt82yFwt4cfofeiJLAfNZXk%2BfkWYPevp40d%2B0snkPba1D8FtCQwyTDD47zGBjqyAfxTAeYaM3mZJ9o9BCgJhn0d8fXS%2FO6ZTTxqrwSftYi8Jrf11R2oMKWnlWzzVoJCsIkeWYs0cxytRs7N6KE1FSSB1Y5MkbxC98vs%2BQeNI3eYXBXj0%2BUpkJLE8Q74gL1lWJo%2B5D4p7WJlG3g%2BBA%2BLW9UFTQ44c2Js2TFR9b0AJGhj5mVyEt5u%2BT%2FsuRpGhrcAkcNiKLEx7K5l36DsSOHZ4JSggc43FWLv76erQxZm%2FIqyKvo%3D&X-Amz-SignedHeaders=host&X-Amz-Signature=e5cfa41dde3e64eb373054c61e0cc214f07069215b583159abb5565dce921a80"
    },
    "permissions": [],
    "submission_state": "open",
    "default_currency": "usd",
    "awards_miles": false,
    "offers_bounties": true,
    "state": "public_mode",
    "only_cleared_hackers": false,
    "pentest_feature_enabled?": false,
    "pentest_retesting_ends_at": null,
    "profile": {
      "name": "Internet Bug Bounty",
      "twitter_handle": "",
      "website": "https://www.hackerone.com/internet-bug-bounty",
      "about": "The Internet Bug Bounty rewards security research into vulnerabilities impacting Open Source Software Projects."
    }
  },
  "has_bounty?": true,
  "can_view_team": true,
  "can_view_report": true,
  "is_external_bug": false,
  "is_published": false,
  "is_participant": false,
  "has_collaborators": false,
  "submitted_by_team_member": false,
  "submitted_with_assistant": false,
  "stage": 4,
  "public": true,
  "visibility": "full",
  "cve_ids": [
    "CVE-2021-4044"
  ],
  "singular_disclosure_disabled": false,
  "disclosed_at": "2022-01-20T23:40:13.396Z",
  "bug_reporter_agreed_on_going_public_at": "2022-01-20T23:40:13.251Z",
  "team_member_agreed_on_going_public_at": "2022-01-20T20:05:18.475Z",
  "comments_closed?": false,
  "facebook_team?": false,
  "team_private?": false,
  "vulnerability_information": "Internally libssl in OpenSSL calls X509_verify_cert() on the client side to\nverify a certificate supplied by a server. That function may return a negative\nreturn value to indicate an internal error (for example out of memory). Such a\nnegative return value is mishandled by OpenSSL and will cause an IO function\n(such as SSL_connect() or SSL_do_handshake()) to not indicate success and a\nsubsequent call to SSL_get_error() to return the value\nSSL_ERROR_WANT_RETRY_VERIFY. This return value is only supposed to be returned\nby OpenSSL if the application has previously called\nSSL_CTX_set_cert_verify_callback(). Since most applications do not do this the\nSSL_ERROR_WANT_RETRY_VERIFY return value from SSL_get_error() will be totally\nunexpected and applications may not behave correctly as a result. The exact\nbehaviour will depend on the application but it could result in crashes,\ninfinite loops or other similar incorrect responses.\n\nThis issue is made more serious in combination with a separate bug in OpenSSL\n3.0 that will cause X509_verify_cert() to indicate an internal error when\nprocessing a certificate chain. This will occur where a certificate does not\ninclude the Subject Alternative Name extension but where a Certificate Authority\nhas enforced name constraints. This issue can occur even with valid chains.\n\n## Impact\n\nBy combining the two issues an attacker could induce incorrect, application\ndependent behaviour.\n\nOpenSSL 3.0.0 SSL/TLS clients are affected by this issue.",
  "bounty_amount": "1200.0",
  "formatted_bounty": "$1,200",
  "weakness": {
    "id": 28,
    "name": "Improper Certificate Validation"
  },
  "original_report_id": null,
  "original_report_url": null,
  "attachments": [],
  "allow_singular_disclosure_at": "2022-02-19T20:05:18.607Z",
  "allow_singular_disclosure_after": -113113877.75529453,
  "singular_disclosure_allowed": true,
  "vote_count": 3,
  "voters": [
    "tniessen",
    "official_blackhat13",
    "meispi"
  ],
  "severity": {
    "rating": "medium",
    "author_type": "User"
  },
  "structured_scope": {
    "databaseId": 80989,
    "asset_type": "SOURCE_CODE",
    "asset_identifier": "https://github.com/openssl/openssl",
    "max_severity": "critical"
  },
  "abilities": {
    "assignable_team_members": [],
    "assignable_team_member_groups": []
  },
  "summaries": [
    {
      "id": 122299,
      "category": "team",
      "content": "OpenSSL Security Advisory [14 December 2021]\n\nInvalid handling of X509_verify_cert() internal errors in libssl (CVE-2021-4044)\n\nSeverity: Moderate\n\nInternally libssl in OpenSSL calls X509_verify_cert() on the client side to verify a certificate supplied by a server. That function may return a negative return value to indicate an internal error (for example out of memory). Such a negative return value is mishandled by OpenSSL and will cause an IO function (such as SSL_connect() or SSL_do_handshake()) to not indicate success and a subsequent call to SSL_get_error() to return the value SSL_ERROR_WANT_RETRY_VERIFY. This return value is only supposed to be returned by OpenSSL if the application has previously called SSL_CTX_set_cert_verify_callback(). Since most applications do not do this the\nSSL_ERROR_WANT_RETRY_VERIFY return value from SSL_get_error() will be totally unexpected and applications may not behave correctly as a result. The exact behaviour will depend on the application but it could result in crashes, infinite loops or other similar incorrect responses.\n\nThis issue is made more serious in combination with a separate bug in OpenSSL 3.0 that will cause X509_verify_cert() to indicate an internal error when processing a certificate chain. This will occur where a certificate does not include the Subject Alternative Name extension but where a Certificate Authority has enforced name constraints. This issue can occur even with valid chains.\n\nBy combining the two issues an attacker could induce incorrect, application dependent behaviour.\n\nOpenSSL 3.0.0 SSL/TLS clients are affected by this issue. Users of this version should upgrade to OpenSSL 3.0.1.\n\nOpenSSL 1.1.1 and 1.0.2 are not affected by this issue.\n\nThis issue was reported to OpenSSL on 29th November 2021 by Tobias Nießen. The fix was developed by Matt Caswell and Tobias Nießen.\n\nhttps://www.openssl.org/news/secadv/20211214.txt",
      "updated_at": "2022-01-20T19:55:35.166Z",
      "can_view?": true,
      "can_create?": false,
      "attachments": [],
      "user": {
        "id": 904892,
        "username": "kunderkoffler",
        "name": "Kayla Underkoffler",
        "bio": null,
        "cleared": false,
        "verified": false,
        "website": null,
        "location": null,
        "created_at": "2020-01-13T19:26:22.339Z",
        "url": "https://hackerone.com/kunderkoffler",
        "hackerone_triager": false,
        "hackerone_employee": false,
        "user_type": "company",
        "profile_picture_urls": {
          "small": "/assets/avatars/default-14ffa99f59cd01423c64904352cc130ffcb6a802eadfd11777a54485749e60f2.png",
          "medium": "/assets/avatars/default-14ffa99f59cd01423c64904352cc130ffcb6a802eadfd11777a54485749e60f2.png",
          "xtralarge": "/assets/avatars/default-14ffa99f59cd01423c64904352cc130ffcb6a802eadfd11777a54485749e60f2.png"
        }
      }
    },
    {
      "category": "researcher",
      "can_view?": true,
      "can_create?": false
    }
  ]
}
